from game_logic import GameLogic, Action, State

# initie un game logic
game = GameLogic()
game.init_board()
#game.print_board_overview()
#print()
#print("joueur 0 fait un 6 et sort un pion")
game.move_pawn(0, 0, 6, Action.MOVE_OUT)
#game.print_board_overview()
#print()
#print("joueur 1 fait un 6 et sort un pion")
game.move_pawn(1, 0, 6, Action.MOVE_OUT)
#game.print_board_overview()
#print()
#print("avance de 30 cases pion 0 pour voir où il se situe")
game.move_pawn(0, 1, 30, Action.MOVE_FORWARD)
#game.print_board_overview()
#print()
#print("avance de 30 cases pion 1 pour voir où il se situe")
game.move_pawn(1, 1, 30, Action.MOVE_FORWARD)
#game.print_board_overview()
#print()
#print("finir le tour de joueur 0")
game.move_pawn(0, 31, 25, Action.MOVE_FORWARD)
#game.print_board_overview()
#print()
game.move_pawn(1, 31, 25, Action.MOVE_FORWARD)
#game.print_board_overview()
#print()
#print("les joueurs entrent en safe zone")
game.move_pawn(0, 56, 1, Action.ENTER_SAFEZONE)
game.move_pawn(1, 56, 1, Action.ENTER_SAFEZONE)
#game.print_board_overview()
#print("faire goal pour joueur 0")
game.move_pawn(0, 57, 6, Action.REACH_GOAL)
#game.print_board_overview()
game.move_pawn(0,0,6,Action.MOVE_OUT)
game.move_pawn(0,1,55,Action.MOVE_FORWARD)
game.print_board_overview()
game.move_pawn(0,56,6,Action.ENTER_SAFEZONE)
game.print_board_overview()
game.move_pawn(0,62,4,Action.REACH_GOAL)
game.print_board_overview()

print()
print()
# test fin de partie
print(f"joueur {game.is_game_over()} a gagné")
print()
print("joueur 0")
print("my board", game.board[0])
print("adversaire board", game.get_adversaire_relative_overview(1))
print()
print("joueur 1")
print(game.board[1])
print(game.get_adversaire_relative_overview(0))